### ISSUE TITLE
'@stuff' gets turned into a link to a user page even when it shouldn't

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#190] opened 2020-08-28 00:09 UTC
For instance, if there is an @ character in a url, the url gets destroyed in an attempt to link to a user.

Maybe check for a space (or nothingness) before the @ character?

**Comment by Polsaker** [comment] 2020-08-28 00:29
Duplicate of #176

**Closed by Polsaker** 2020-08-28 00:29 UTC
